services:
  whisper:
    container_name: whisper
    build: ./whisper
    restart: on-failure
    volumes:
      - /mnt/sda1/data:/data
    networks:
      - n8n_network
    ports:
      - "5632:5632"

  instaloader:
    container_name: instaloader
    build: ./instaloader
    restart: on-failure
    ports:
      - "5633:5633"
    networks:
      - n8n_network
    volumes:
      - /mnt/sda1/data:/data

networks:
  n8n_network:
    driver: bridge
